export interface StartGamePacket {
  entity_id: bigint;
  runtime_entity_id: bigint;
  player_gamemode: number;
  player_position: { x: number; y: number; z: number };
  rotation: { x: number; y: number };
  seed: bigint;
  biome_type: number;
  biome_name: string;
  dimension: string | number;
  generator: number;
  world_gamemode: number;
  hardcore: boolean;
  difficulty: number;
  spawn_position: { x: number; y: number; z: number };
  achievements_disabled: boolean;
  editor_world_type: string | number;
  created_in_editor: boolean;
  exported_from_editor: boolean;
  day_cycle_stop_time: number;
  edu_offer: number;
  edu_features_enabled: boolean;
  edu_product_uuid: string;
  rain_level: number;
  lightning_level: number;
  has_confirmed_platform_locked_content: boolean;
  is_multiplayer: boolean;
  broadcast_to_lan: boolean;
  xbox_live_broadcast_mode: number;
  platform_broadcast_mode: number;
  enable_commands: boolean;
  is_texturepacks_required: boolean;
  gamerules: any[];
  experiments: any;
  experiments_previously_used: boolean;
  bonus_chest: boolean;
  map_enabled: boolean;
  permission_level: number;
  server_chunk_tick_range: number;
  has_locked_behavior_pack: boolean;
  has_locked_resource_pack: boolean;
  is_from_locked_world_template: boolean;
  msa_gamertags_only: boolean;
  is_from_world_template: boolean;
  is_world_template_option_locked: boolean;
  only_spawn_v1_villagers: boolean;
  persona_disabled: boolean;
  custom_skins_disabled: boolean;
  emote_chat_muted: boolean;
  game_version: string;
  limited_world_width: number;
  limited_world_length: number;
  is_new_nether: boolean;
  edu_resource_uri: any;
  experimental_gameplay_override: boolean;
  chat_restriction_level: string | number;
  disable_player_interactions: boolean;
  server_identifier: string;
  world_identifier: string;
  scenario_identifier: string;
  owner_identifier: string;
  level_id: string;
  world_name: string;
  premium_world_template_id: string;
  is_trial: boolean;
  rewind_history_size: number;
  server_authoritative_block_breaking: boolean;
  current_tick: bigint;
  enchantment_seed: number;
  block_properties: any;
  multiplayer_correlation_id: string;
  server_authoritative_inventory: boolean;
  engine: string;
  property_data: any;
  block_pallette_checksum: bigint;
  world_template_id: string;
  client_side_generation: boolean;
  block_network_ids_are_hashes: boolean;
  server_controlled_sound: boolean;
  raw?: Buffer;
}
