import type { AddEntityPacket } from "./packets/add_entity";
import type { AddItemEntityPacket } from "./packets/add_item_entity";
import type { AddPaintingPacket } from "./packets/add_painting";
import type { AddPlayerPacket } from "./packets/add_player";
import type { AddVolumeEntityPacket } from "./packets/add_volume_entity";
import type { AdventureSettingsPacket } from "./packets/adventure_settings";
import type { AnimatePacket } from "./packets/animate";
import type { AnimateEntityPacket } from "./packets/animate_entity";
import type { AnvilDamagePacket } from "./packets/anvil_damage";
import type { AvailableCommandsPacket } from "./packets/available_commands";
import type { BlockEntityDataPacket } from "./packets/block_entity_data";
import type { BlockEventPacket } from "./packets/block_event";
import type { BlockPickRequestPacket } from "./packets/block_pick_request";
import type { BossEventPacket } from "./packets/boss_event";
import type { CameraPacket } from "./packets/camera";
import type { CameraShakePacket } from "./packets/camera_shake";
import type { ChangeDimensionPacket } from "./packets/change_dimension";
import type { ChunkRadiusUpdatePacket } from "./packets/chunk_radius_update";
import type { ClientCacheBlobStatusPacket } from "./packets/client_cache_blob_status";
import type { ClientCacheMissResponsePacket } from "./packets/client_cache_miss_response";
import type { ClientCacheStatusPacket } from "./packets/client_cache_status";
import type { ClientToServerHandshakePacket } from "./packets/client_to_server_handshake";
import type { ClientboundMapItemDataPacket } from "./packets/clientbound_map_item_data";
import type { CodeBuilderPacket } from "./packets/code_builder";
import type { CodeBuilderSourcePacket } from "./packets/code_builder_source";
import type { CommandBlockUpdatePacket } from "./packets/command_block_update";
import type { CommandOutputPacket } from "./packets/command_output";
import type { CommandRequestPacket } from "./packets/command_request";
import type { CompletedUsingItemPacket } from "./packets/completed_using_item";
import type { ContainerClosePacket } from "./packets/container_close";
import type { ContainerOpenPacket } from "./packets/container_open";
import type { ContainerSetDataPacket } from "./packets/container_set_data";
import type { CorrectPlayerMovePredictionPacket } from "./packets/correct_player_move_prediction";
import type { CraftingDataPacket } from "./packets/crafting_data";
import type { CraftingEventPacket } from "./packets/crafting_event";
import type { CreativeContentPacket } from "./packets/creative_content";
import type { DeathInfoPacket } from "./packets/death_info";
import type { DebugInfoPacket } from "./packets/debug_info";
import type { DebugRendererPacket } from "./packets/debug_renderer";
import type { DisconnectPacket } from "./packets/disconnect";
import type { EducationSettingsPacket } from "./packets/education_settings";
import type { EmotePacket } from "./packets/emote";
import type { EmoteListPacket } from "./packets/emote_list";
import type { EntityEventPacket } from "./packets/entity_event";
import type { EntityPickRequestPacket } from "./packets/entity_pick_request";
import type { EventPacket } from "./packets/event";
import type { FilterTextPacketPacket } from "./packets/filter_text_packet";
import type { GameRulesChangedPacket } from "./packets/game_rules_changed";
import type { GuiDataPickItemPacket } from "./packets/gui_data_pick_item";
import type { HurtArmorPacket } from "./packets/hurt_armor";
import type { InteractPacket } from "./packets/interact";
import type { InventoryContentPacket } from "./packets/inventory_content";
import type { InventorySlotPacket } from "./packets/inventory_slot";
import type { InventoryTransactionPacket } from "./packets/inventory_transaction";
import type { ItemRegistryPacket } from "./packets/item_registry";
import type { ItemStackRequestPacket } from "./packets/item_stack_request";
import type { ItemStackResponsePacket } from "./packets/item_stack_response";
import type { LevelChunkPacket } from "./packets/level_chunk";
import type { LevelEventPacket } from "./packets/level_event";
import type { LevelSoundEventOldPacket } from "./packets/level_sound_event_old";
import type { LoginPacket } from "./packets/login";
import type { MapInfoRequestPacket } from "./packets/map_info_request";
import type { MobArmorEquipmentPacket } from "./packets/mob_armor_equipment";
import type { MobEffectPacket } from "./packets/mob_effect";
import type { MobEquipmentPacket } from "./packets/mob_equipment";
import type { MotionPredictionHintsPacket } from "./packets/motion_prediction_hints";
import type { MoveEntityPacket } from "./packets/move_entity";
import type { MovePlayerPacket } from "./packets/move_player";
import type { MultiplayerSettingsPacket } from "./packets/multiplayer_settings";
import type { NetworkSettingsPacket } from "./packets/network_settings";
import type { NetworkStackLatencyPacket } from "./packets/network_stack_latency";
import type { ViolationWarningPacket } from "./packets/packet_violation_warning";
import type { PlayStatusPacket } from "./packets/play_status";
import type { PlayerActionPacket } from "./packets/player_action";
import type { PlayerArmorDamagePacket } from "./packets/player_armor_damage";
import type { PlayerAuthInputPacket } from "./packets/player_auth_input";
import type { PlayerEnchantOptionsPacket } from "./packets/player_enchant_options";
import type { PlayerFogPacket } from "./packets/player_fog";
import type { PlayerHotbarPacket } from "./packets/player_hotbar";
import type { PlayerInputPacket } from "./packets/player_input";
import type { PlayerListPacket } from "./packets/player_list";
import type { PlayerSkinPacket } from "./packets/player_skin";
import type { PositionTrackingDbBroadcastPacket } from "./packets/position_tracking_db_broadcast";
import type { PositionTrackingDbRequestPacket } from "./packets/position_tracking_db_request";
import type { RemoveEntityPacket } from "./packets/remove_entity";
import type { RemoveVolumeEntityPacket } from "./packets/remove_volume_entity";
import type { RequestAbilityPacket } from "./packets/request_ability";
import type { RequestChunkRadiusPacket } from "./packets/request_chunk_radius";
import type { RequestNetworkSettingsPacket } from "./packets/request_network_settings";
import type { RequestPermissionsPacket } from "./packets/request_permissions";
import type { ResourcePackChunkDataPacket } from "./packets/resource_pack_chunk_data";
import type { ResourcePackChunkRequestPacket } from "./packets/resource_pack_chunk_request";
import type { ResourcePackClientResponsePacket } from "./packets/resource_pack_client_response";
import type { ResourcePackDataInfoPacket } from "./packets/resource_pack_data_info";
import type { ResourcePackStackPacket } from "./packets/resource_pack_stack";
import type { ResourcePacksInfoPacket } from "./packets/resource_packs_info";
import type { RespawnPacket } from "./packets/respawn";
import type { RiderJumpPacket } from "./packets/rider_jump";
import type { ServerPostMovePacket } from "./packets/server_post_move";
import type { ServerStatsPacket } from "./packets/server_stats";
import type { ServerToClientHandshakePacket } from "./packets/server_to_client_handshake";
import type { SetCommandsEnabledPacket } from "./packets/set_commands_enabled";
import type { SetDifficultyPacket } from "./packets/set_difficulty";
import type { SetEntityDataPacket } from "./packets/set_entity_data";
import type { SetEntityLinkPacket } from "./packets/set_entity_link";
import type { SetEntityMotionPacket } from "./packets/set_entity_motion";
import type { SetHealthPacket } from "./packets/set_health";
import type { SetLocalPlayerAsInitializedPacket } from "./packets/set_local_player_as_initialized";
import type { SetPlayerGameTypePacket } from "./packets/set_player_game_type";
import type { SetSpawnPositionPacket } from "./packets/set_spawn_position";
import type { SetTimePacket } from "./packets/set_time";
import type { SettingsCommandPacket } from "./packets/settings_command";
import type { ShowCreditsPacket } from "./packets/show_credits";
import type { SimpleEventPacket } from "./packets/simple_event";
import type { SpawnExperienceOrbPacket } from "./packets/spawn_experience_orb";
import type { StartGamePacket } from "./packets/start_game";
import type { SyncEntityPropertyPacket } from "./packets/sync_entity_property";
import type { TakeItemEntityPacket } from "./packets/take_item_entity";
import type { TextPacket } from "./packets/text";
import type { TickSyncPacket } from "./packets/tick_sync";
import type { ToastRequestPacket } from "./packets/toast_request";
import type { TransferPacket } from "./packets/transfer";
import type { UpdateAttributesPacket } from "./packets/update_attributes";
import type { UpdateBlockPacket } from "./packets/update_block";
import type { UpdateEquipmentPacket } from "./packets/update_equipment";
import type { UpdatePlayerGameTypePacket } from "./packets/update_player_game_type";
import type { UpdateSoftEnumPacket } from "./packets/update_soft_enum";
import type { UpdateTradePacket } from "./packets/update_trade";

export interface Events {
  add_entity: (packet: AddEntityPacket) => void;
  add_item_entity: (packet: AddItemEntityPacket) => void;
  add_painting: (packet: AddPaintingPacket) => void;
  add_player: (packet: AddPlayerPacket) => void;
  add_volume_entity: (packet: AddVolumeEntityPacket) => void;
  adventure_settings: (packet: AdventureSettingsPacket) => void;
  animate: (packet: AnimatePacket) => void;
  animate_entity: (packet: AnimateEntityPacket) => void;
  anvil_damage: (packet: AnvilDamagePacket) => void;
  available_commands: (packet: AvailableCommandsPacket) => void;
  block_entity_data: (packet: BlockEntityDataPacket) => void;
  block_event: (packet: BlockEventPacket) => void;
  block_pick_request: (packet: BlockPickRequestPacket) => void;
  boss_event: (packet: BossEventPacket) => void;
  camera: (packet: CameraPacket) => void;
  camera_shake: (packet: CameraShakePacket) => void;
  change_dimension: (packet: ChangeDimensionPacket) => void;
  chunk_radius_update: (packet: ChunkRadiusUpdatePacket) => void;
  client_cache_blob_status: (packet: ClientCacheBlobStatusPacket) => void;
  client_cache_miss_response: (packet: ClientCacheMissResponsePacket) => void;
  client_cache_status: (packet: ClientCacheStatusPacket) => void;
  client_to_server_handshake: (packet: ClientToServerHandshakePacket) => void;
  clientbound_map_item_data: (packet: ClientboundMapItemDataPacket) => void;
  code_builder: (packet: CodeBuilderPacket) => void;
  code_builder_source: (packet: CodeBuilderSourcePacket) => void;
  command_block_update: (packet: CommandBlockUpdatePacket) => void;
  command_output: (packet: CommandOutputPacket) => void;
  command_request: (packet: CommandRequestPacket) => void;
  completed_using_item: (packet: CompletedUsingItemPacket) => void;
  container_close: (packet: ContainerClosePacket) => void;
  container_open: (packet: ContainerOpenPacket) => void;
  container_set_data: (packet: ContainerSetDataPacket) => void;
  correct_player_move_prediction: (
    packet: CorrectPlayerMovePredictionPacket,
  ) => void;
  crafting_data: (packet: CraftingDataPacket) => void;
  crafting_event: (packet: CraftingEventPacket) => void;
  creative_content: (packet: CreativeContentPacket) => void;
  death_info: (packet: DeathInfoPacket) => void;
  debug_info: (packet: DebugInfoPacket) => void;
  debug_renderer: (packet: DebugRendererPacket) => void;
  disconnect: (packet: DisconnectPacket) => void;
  education_settings: (packet: EducationSettingsPacket) => void;
  emote: (packet: EmotePacket) => void;
  emote_list: (packet: EmoteListPacket) => void;
  entity_event: (packet: EntityEventPacket) => void;
  entity_pick_request: (packet: EntityPickRequestPacket) => void;
  event: (packet: EventPacket) => void;
  filter_text_packet: (packet: FilterTextPacketPacket) => void;
  game_rules_changed: (packet: GameRulesChangedPacket) => void;
  gui_data_pick_item: (packet: GuiDataPickItemPacket) => void;
  hurt_armor: (packet: HurtArmorPacket) => void;
  interact: (packet: InteractPacket) => void;
  inventory_content: (packet: InventoryContentPacket) => void;
  inventory_slot: (packet: InventorySlotPacket) => void;
  inventory_transaction: (packet: InventoryTransactionPacket) => void;
  item_registry: (packet: ItemRegistryPacket) => void;
  item_stack_request: (packet: ItemStackRequestPacket) => void;
  item_stack_response: (packet: ItemStackResponsePacket) => void;
  level_chunk: (packet: LevelChunkPacket) => void;
  level_event: (packet: LevelEventPacket) => void;
  level_sound_event_old: (packet: LevelSoundEventOldPacket) => void;
  login: (packet: LoginPacket) => void;
  map_info_request: (packet: MapInfoRequestPacket) => void;
  mob_armor_equipment: (packet: MobArmorEquipmentPacket) => void;
  mob_effect: (packet: MobEffectPacket) => void;
  mob_equipment: (packet: MobEquipmentPacket) => void;
  motion_prediction_hints: (packet: MotionPredictionHintsPacket) => void;
  move_entity: (packet: MoveEntityPacket) => void;
  move_player: (packet: MovePlayerPacket) => void;
  multiplayer_settings: (packet: MultiplayerSettingsPacket) => void;
  network_settings: (packet: NetworkSettingsPacket) => void;
  network_stack_latency: (packet: NetworkStackLatencyPacket) => void;
  violation_warning: (packet: ViolationWarningPacket) => void;
  play_status: (packet: PlayStatusPacket) => void;
  player_action: (packet: PlayerActionPacket) => void;
  player_armor_damage: (packet: PlayerArmorDamagePacket) => void;
  player_auth_input: (packet: PlayerAuthInputPacket) => void;
  player_enchant_options: (packet: PlayerEnchantOptionsPacket) => void;
  player_fog: (packet: PlayerFogPacket) => void;
  player_hotbar: (packet: PlayerHotbarPacket) => void;
  player_input: (packet: PlayerInputPacket) => void;
  player_list: (packet: PlayerListPacket) => void;
  player_skin: (packet: PlayerSkinPacket) => void;
  position_tracking_db_broadcast: (
    packet: PositionTrackingDbBroadcastPacket,
  ) => void;
  position_tracking_db_request: (
    packet: PositionTrackingDbRequestPacket,
  ) => void;
  remove_entity: (packet: RemoveEntityPacket) => void;
  remove_volume_entity: (packet: RemoveVolumeEntityPacket) => void;
  request_ability: (packet: RequestAbilityPacket) => void;
  request_chunk_radius: (packet: RequestChunkRadiusPacket) => void;
  request_network_settings: (packet: RequestNetworkSettingsPacket) => void;
  request_permissions: (packet: RequestPermissionsPacket) => void;
  resource_pack_chunk_data: (packet: ResourcePackChunkDataPacket) => void;
  resource_pack_chunk_request: (packet: ResourcePackChunkRequestPacket) => void;
  resource_pack_client_response: (
    packet: ResourcePackClientResponsePacket,
  ) => void;
  resource_pack_data_info: (packet: ResourcePackDataInfoPacket) => void;
  resource_pack_stack: (packet: ResourcePackStackPacket) => void;
  resource_packs_info: (packet: ResourcePacksInfoPacket) => void;
  respawn: (packet: RespawnPacket) => void;
  rider_jump: (packet: RiderJumpPacket) => void;
  server_post_move: (packet: ServerPostMovePacket) => void;
  server_stats: (packet: ServerStatsPacket) => void;
  server_to_client_handshake: (packet: ServerToClientHandshakePacket) => void;
  set_commands_enabled: (packet: SetCommandsEnabledPacket) => void;
  set_difficulty: (packet: SetDifficultyPacket) => void;
  set_entity_data: (packet: SetEntityDataPacket) => void;
  set_entity_link: (packet: SetEntityLinkPacket) => void;
  set_entity_motion: (packet: SetEntityMotionPacket) => void;
  set_health: (packet: SetHealthPacket) => void;
  set_local_player_as_initialized: (
    packet: SetLocalPlayerAsInitializedPacket,
  ) => void;
  set_player_game_type: (packet: SetPlayerGameTypePacket) => void;
  set_spawn_position: (packet: SetSpawnPositionPacket) => void;
  set_time: (packet: SetTimePacket) => void;
  settings_command: (packet: SettingsCommandPacket) => void;
  show_credits: (packet: ShowCreditsPacket) => void;
  simple_event: (packet: SimpleEventPacket) => void;
  spawn_experience_orb: (packet: SpawnExperienceOrbPacket) => void;
  start_game: (packet: StartGamePacket) => void;
  sync_entity_property: (packet: SyncEntityPropertyPacket) => void;
  take_item_entity: (packet: TakeItemEntityPacket) => void;
  text: (packet: TextPacket) => void;
  tick_sync: (packet: TickSyncPacket) => void;
  toast_request: (packet: ToastRequestPacket) => void;
  transfer: (packet: TransferPacket) => void;
  update_attributes: (packet: UpdateAttributesPacket) => void;
  update_block: (packet: UpdateBlockPacket) => void;
  update_equipment: (packet: UpdateEquipmentPacket) => void;
  update_player_game_type: (packet: UpdatePlayerGameTypePacket) => void;
  update_soft_enum: (packet: UpdateSoftEnumPacket) => void;
  update_trade: (packet: UpdateTradePacket) => void;
  session: () => void;
  close: () => void;
  error: () => void;
  disconnect: () => void;
  connect_allowed: () => void;
}
